apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unikalo-mongodb
  namespace: argocd
spec:
  project: koden-clients
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.6.5
    chart: mongodb
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/koden-process/unikalo-mongodb-k8s/refs/heads/main/values.yaml
      values: |
        auth:
          existingSecret: unikalo-mongodb-secret
          usernames:
            - unikalo
          databases:
            - meow
  destination:
    server: https://kubernetes.default.svc
    namespace: koden-clients
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
